# On every push this script is executed
on:
  push:
    branches: [ main ]
name: Build and deploy GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          GITHUB_TOKEN: ${{secrets.REPO_TOKEN}}
          BUILD_THEMES: false
